### ISSUE TITLE
Continue the series please

### ISSUE THREAD

**Issue by IsraelOrtuno** [adrianjost/nuxtjs-theming#1]
Hey @adrianjost ! That serie was pretty interesting! Can't wait to get more articles about how you designed the rest of the architecture, facing the same problem and it's driving me mad 😅 Amazing work.

**Comment by adrianjost** [comment]
Wow, you must have looked pretty hard to find this repo 😅
So far none of the articles are officially published yet, because I haven't had time to write the other chapters. But your comment has motivated me to continue soon.
Thanks for your kind words!
I will keep you updated in this issue.

**Comment by IsraelOrtuno** [comment]
I am experimenting using `extendRoutes` function from `router` property to replace matching pages, something like this just worked:

```
  router: {
    extendRoutes(routes, resolve) {
      routes = routes.map(route => {
        if (route.name == 'about') {
          route.component = '/Users/israel/Code/Boards/jobbb-front/src/theme/about.vue'
        } 

        return route
      })
    }
  }
```

So I guess I can make this dynamic and look into a theme folder for the matching route chunkName.

**Comment by IsraelOrtuno** [comment]
Ended up with something like this:

```
  router: {
    extendRoutes(routes, resolve) {
      routes.map(route => { 
        const path = resolve(`src/theme/${route.chunkName}.vue`)

        if (fs.existsSync(path)) {
          route.component = path
        }

        return route
      })
    }
  },
```

And pages should be under `src/theme/pages`. Matching pages will be replaced, others will just be skipped. Works pretty nice so far 😅

**Comment by adrianjost** [comment]
Yes, that should work. I've had the same plan to do this but hadn't had time to try it out.

Can I use your code snippet as an example (maybe slightly modified) in one of my articles?
Of course I would reference you!

**Comment by IsraelOrtuno** [comment]
Sure feel free, thanks for the inspiration.
